scrap/scrap/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('scrapapp.urls')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

scrap/scrapapp/urls.py
from django.conf.urls import url,include
from . import views
from django.contrib.auth import views as auth_views



app_name='scrapapp'
urlpatterns = [
    url(r'^home/$', views.home),
    url(r'^adminlogin/$', views.adminlogin),
    url(r'^validateuser/$',views.validate_user),
    url(r'^index/$', views.index),
    url(r'^dealerlogin/$',views.dealerlogin),
    url(r'^sellerlogin/$', views.sellerlogin),
    url(r'^dealerregister/$', views.dealerreg),
    url(r'^sellerregister/$', views.sellerreg),
    url(r'^ads/(?P<id>[0-9]+)/$', views.adsid),
    url(r'^cart/$',views.cart),
    url(r'^sellerlogin/bids/$',views.bids),
    url(r'^sellerlogin/bids/(?P<id>[0-9]+)/$',views.viewbids),
    url(r'^recentbids/$',views.recentbids),
    url(r'^deals/$',views.deals),
    url(r'^deals/(?P<id>[0-9]+)/$', views.dealsid),
    url(r'^codeverify/$',views.codeverify),
    url(r'^addtocart/$',views.addtocart),
    url(r'^acceptbid/$', views.acceptbid),
    url(r'^wallet/$', views.wallet),
    url(r'^stats/$', views.statistics),
    url(r'^logout/$',views.logout_view),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    url(r'^test/$', views.test),

]

scrap/scrapapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import User
from django.forms import forms,ModelForm
from datetime import datetime,timedelta


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user')
    is_dealer = models.BooleanField(default=False)
    is_seller = models.BooleanField(default=True)
    ph_no = models.CharField(max_length=10)
    address = models.CharField(max_length=50)
    pincode = models.CharField(max_length=6)
    city = models.CharField(max_length= 20)
    street = models.CharField(max_length=25,null=True)
    state = models.CharField(max_length=25)
    reg_image = models.ImageField()
    landmark = models.CharField(max_length=30)
    reg_id = models.CharField(max_length=20)
    ratings = models.IntegerField(null=True)
    verify = models.CharField(max_length=6,default='')
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


class Product(models.Model):
    pname = models.CharField(max_length=20)
    baseprice =models.IntegerField()
    date = models.DateTimeField(default=datetime.now, blank=True)

    def __str__(self):
        return self.pname


class Ads(models.Model):
    pname = models.ForeignKey(Product,on_delete=models.CASCADE)
    username = models.ForeignKey(UserProfile, null=True)
    date = models.DateTimeField(default=datetime.now, blank=True)
    quantity = models.IntegerField()
    price = models.IntegerField()
    is_actibe = models.BooleanField(default= True)
    club_friend = models.BooleanField(default=False)
    is_bidded = models.BooleanField(default=False)
    expires = models.DateTimeField(default=datetime.now()+timedelta(days=7))
    is_new = models.BooleanField(default=True)

    def __str__(self):
        return '%s %s %s' %(format(self.pk),self.pname,self.username)


class Expired_Ad(models.Model):
    user = models.ForeignKey(UserProfile,on_delete=models.CASCADE,unique=False)
    ad = models.OneToOneField(Ads,on_delete=models.CASCADE)

    def __str__(self):
        return '%s %s' %(self.user,self.ad)

class Bid(models.Model):
    ad_id = models.ForeignKey(Ads,on_delete=models.CASCADE)
    bid_amount = models.IntegerField()
    bid_time = models.DateTimeField(default=datetime.now,null = True)
    bidded_by = models.ForeignKey(UserProfile,on_delete=models.CASCADE,)
    product = models.ForeignKey(Product,on_delete=models.CASCADE)

    def __str__(self):
        return 'bid for ad( no.%s) by %s is %srs' %(format(self.ad_id),format(self.bidded_by),format(self.bid_amount))

class Bid_Detail(models.Model):
    seller_name = models.ForeignKey(UserProfile,on_delete=models.CASCADE)
    ad = models.OneToOneField(Ads,on_delete=models.CASCADE)
    bid_detail = models.OneToOneField(Bid,on_delete=models.CASCADE)
    product = models.ForeignKey(Product,on_delete=models.CASCADE,)
    amount = models.IntegerField()
    bidder_name = models.CharField(max_length=30,)

    def __str__(self):
        return '%s %s %s %s'%(self.seller_name,self.ad,self.bid_detail,self.product)


class ContactUs(models.Model):
    Name = models.CharField(max_length=30)
    place = models.CharField(max_length=30)
    mobile = models.CharField(max_length=10)
    message = models.CharField(max_length=500)
    email = models.EmailField()
    status = models.BooleanField(default=True)
    reply = models.CharField(max_length=500,default='')

    def __str__(self):
        return '%s %s' %(self.Name,self.mobile)

class Cart(models.Model):
    user = models.OneToOneField(UserProfile,on_delete=models.CASCADE)
    product =models.ForeignKey(Product,on_delete=models.CASCADE,null=True)
    ads = models.ForeignKey(Ads,on_delete=models.CASCADE)
    bid = models.ForeignKey(Bid,on_delete=models.CASCADE,null=True)

    def __str__(self):
        return '%s %s %s'%(self.user,self.product,self.ads)

class Wallet(models.Model):
    user = models.OneToOneField(UserProfile,on_delete=models.CASCADE)
    amount = models.IntegerField(default=0)

    def __str__(self):
        return '%s %s' %(format(self.user),self.amount)

class Transactions(models.Model):
    user = models.OneToOneField(UserProfile,on_delete=models.CASCADE)
    ad = models.OneToOneField(Ads,on_delete=models.CASCADE)
    is_rated = models.BooleanField(default=False)
    bid_detail = models.OneToOneField(Bid_Detail,on_delete=models.CASCADE)

    def __str__(self):
        return '%s %s %s' %(format(self.user),self.ad,format(self.id))


class ProductProfit(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    user = models.ForeignKey(UserProfile,on_delete=models.CASCADE)
    sell_price = models.IntegerField()

    def __str__(self):
        return '%s %s' %(format(self.product),self.user)

class Profit(models.Model):
    user = models.ForeignKey(UserProfile,on_delete=models.CASCADE)
    product = models.OneToOneField(ProductProfit,on_delete=models.CASCADE)
    quantity = models.IntegerField()

    def __str__(self):
        return format(self.user)

scrap/scrapapp/forms.py
from .models import *
from django.forms import ModelForm
from django.db import models
from django.contrib.auth.models import User
from django import forms

class userform(ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username','password','email']


class Dealer(ModelForm):
    class Meta:
        model=UserProfile

        fields=['ph_no','address','pincode','city','reg_id','reg_image']



class Seller(ModelForm):
    class Meta:
        model=UserProfile

        fields=['ph_no','address','pincode','city','landmark',]


class Adsform(ModelForm):
    class Meta:
        model = Ads
        fields = ['pname','quantity','price','club_friend']


class Bidform(ModelForm):
    class Meta:
        model = Bid
        fields = ['bid_amount','bid_time']

class Contactform(ModelForm):
    class Meta:
        model = ContactUs
        exclude = []

scrap/scrapapp/views.py
from django.db import transaction
from django.shortcuts import render, get_object_or_404
from django.http import *
from django.template.loader import get_template
from django.template import Context
from django.template.context_processors import request
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth import login, logout, authenticate
from django.core.serializers.json import DjangoJSONEncoder
from django.template import loader
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.forms import modelformset_factory
from .forms import *
from datetime import datetime,date
from django.apps import *
from django.core.mail import send_mail, BadHeaderError,EmailMultiAlternatives
import random,traceback,json
from django.utils.safestring import mark_safe
from scrapapp.serializers import AdSerializer, ProductSerializer
from rest_framework import serializers
from django.core import serializers
from collections import Counter
import jsonpickle
from django.http import JsonResponse




def My_User(user):
    currentuser = UserProfile.objects.get(user=user)
    return currentuser

def sendmail(user,subject,message):
    html = get_template('scrapapp/email.html')
    try:
        print(user.email)
        currentuser = My_User(user)
        toaddress=[user.email]
        username = Context({'user':currentuser.user})
        htmlcontent = html.render({'username':username,'message':message})

    except:
        toaddress = [user]
        username = user
        htmlcontent = html.render({'username':username,'message':message})
        print("else statement is reached")

    emaildetail = EmailMultiAlternatives(subject,message,'scrappyteam.in@gmail.com',toaddress)
    emaildetail.attach_alternative(htmlcontent,'text/html')
    try:
        emaildetail.send()
    except BadHeaderError:
        return HttpResponse('Invalid header found.')


def validate_user(request):
    username = request.GET.get('username')
    data = {'is_taken':User.objects.filter(username__iexact=username).exists()}
    return JsonResponse(data)

def adminlogin(request):
    if not request.user.is_superuser:
        return HttpResponseRedirect('/home/')
    contact_msg = ContactUs.objects.filter(status=True)
    if request.POST:
        answer = format(request.POST.get('message'))
        print("answer = "+answer)
        id = format(request.POST.get('id'))
        try:
            reply_msg = ContactUs.objects.get(id=id)
            message = answer
            subject = "regarding you enquiry about "+format(reply_msg.message)
            sendmail(format(reply_msg.email),subject,message)
            reply_msg.status = False
            reply_msg.reply = answer
            reply_msg.save()
            print(answer+id)
            status = {'status':"yes"}
            return JsonResponse(status)
        except:
            status = {'status': "no"}
            return JsonResponse(status)
    return render(request,'scrapapp/admin.html',{'messages':contact_msg})

def eeee():
    ads = Bid.objects.all()
    for ad in ads:
        print(ad.bidded_by)

    date = datetime.now()
    newdate = date + timedelta(days=7)
    for ad in ads:
        ad.is_actibe = True
        ad.is_new= True
        ad.expires = newdate
        ad.save()
    return



def home(request):
    #eeee()
    if request.user.is_authenticated:
        try:
            user = UserProfile.objects.get(user=request.user)
        except:
            user = User.objects.get(username=request.user)
            if user.is_superuser:
                return HttpResponseRedirect('/adminlogin/')
        if not user.is_active:
            return HttpResponseRedirect('/codeverify/')
        if user.is_seller :
            return HttpResponseRedirect("/sellerlogin/")
        elif user.is_dealer:
            return HttpResponseRedirect("/dealerlogin/")

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        print(username, password)

        user = authenticate(username=username, password=password)
        superuser = User.objects.get(username=username)
        if superuser.is_superuser:
            login(request,superuser)
            return HttpResponseRedirect('/adminlogin/')
        if user:
            login(request, user)
            userstatus = UserProfile.objects.get(user=user)
            print(userstatus)
            if userstatus.is_dealer:
                return HttpResponseRedirect('/dealerlogin/')
            else:
                return HttpResponseRedirect('/sellerlogin/')
        else:
            error = "Invalid Credentials"
            return render(request, 'scrapapp/home.html', {'error': error})

    else:
        dealer = '/dealerregister/'
        seller = '/sellerregister/'
        return render(request, 'scrapapp/home.html', {'dealerreg': dealer, 'sellerreg': seller})


def dealerreg(request):
    if request.method == 'POST':
        userformset = userform(request.POST)
        formset = Dealer(request.POST, request.FILES)
        if userformset.is_valid() and formset.is_valid():
            myuser = userformset.save()
            password = request.POST.get('password')
            myuser.set_password(request.POST['password'])
            myuser.save()
            profile = formset.save(commit=False)
            profile.user = myuser
            profile.is_dealer = True
            profile.is_seller = False
            profile.verify = verify()
            try:
                profile.save()
                subject = format(profile.user)+", Welcome to Scrappy Team !"
                message = format(profile.user)+", your Verification Code is : "+format(profile.verify)+" "
                sendmail(profile.user,subject,message)
            except:
                traceback.print_exc()
                return HttpResponse("couldnt register")
            status = 'Registration successful'
            user = authenticate(username=profile.user, password=password)
            if user:
                login(request, user)
            return HttpResponseRedirect('/codeverify/')
            #return render(request, 'scrapapp/register.html', {'status': status, 'form': formset, 'user': userformset})
        else:
            status = 'Registration unsuccessful'
            return render(request, 'scrapapp/register.html', {'status': status, 'form': formset, 'user': userformset})
    else:
        userformset = 'dealer'
        formset = 'dealer'
        return render(request, 'scrapapp/register.html', {'form': formset, 'user': userformset})


def sellerreg(request):
    if request.POST:
        userformset = userform(request.POST)
        formset = Seller(request.POST)
        if userformset.is_valid() and formset.is_valid():
            myuser = userformset.save()
            password = request.POST.get('password')
            print(password)
            myuser.set_password(password)
            myuser.save()
            profile = formset.save(commit=False)
            profile.user = myuser
            profile.verify = verify()
            try:
                profile.save()
                subject = "Welcome to scrappy team"
                message = "Hearty welcome dear "+format(profile.user)+"\n your verfications code is "+format(profile.verify)+""
                sendmail(profile.user,subject,message)
            except:
                print(profile.user)
               # return HttpResponse("unsuccessful seller reg")
                traceback.print_exc()
            status = 'Registration successful'
            user = authenticate(username=profile.user, password=password)
            if user:
                login(request, user)
            print(user)
            return HttpResponseRedirect('/codeverify/')
           # return render(request, 'scrapapp/register.html', {'status': status, 'form': formset, 'user': userformset})
        else:
            status = 'Registration unsuccessful'
            return render(request, 'scrapapp/register.html', {'status': formset.errors, 'form': formset, 'user': userformset})
    else:
        userformset = 'seller'
        formset = 'seller'
        return render(request, 'scrapapp/register.html', {'form': formset, 'user': userformset})



def verify():
   number = format(random.randint(100000,999999))
   return number

@user_passes_test(User, login_url='/home/')
def codeverify(request):
    if not request.user.is_authenticated:
        HttpResponseRedirect('/home/')
    if request.POST:
        code = request.POST.get('code')
        print(code)
        currentuser = My_User(request.user)
        print(currentuser.verify)
        if code == currentuser.verify:
            currentuser.is_active = True
            currentuser.save()
            return HttpResponseRedirect('/home/')
        else:
            return HttpResponse("Invalid code")
    else:
        return render(request,'scrapapp/verfication.html',{'user':request.user})


def check_expiry():
    ads = Ads.objects.all()
    nowdate = date.today()
    print(ads)
    for ad in ads:
        #print(ad)
        if nowdate > datetime.date(ad.expires):
            print("expired ad = ")
            print(ad)
            ad.is_actibe = False
            ad.save()
            expired_ad = Expired_Ad()
            expired_ad.user = ad.username
            expired_ad.id = ad.id
            expired_ad.ad = ad
            expired_ad.save()
    return

@user_passes_test(User, login_url='/home/')
def dealerlogin(request):
    if not request.user.is_authenticated:
        alert = "You must login "
        return HttpResponseRedirect("/home/")


    id = '/logout/'

    check_expiry()

    myuser = UserProfile.objects.get(user=request.user)
    print(myuser.is_dealer)
    if not myuser.is_dealer:
        alert = "You must login "
        return HttpResponseRedirect("/home/")
    if not myuser.is_active:
        return HttpResponseRedirect('/codeverify/')

scrap/scrapapp/templates/scrapapp/ad_detail - Copy.html
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My Ads</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Coda" rel="stylesheet">
    <link href="{% static "css/materialize.css" %}" media="screen,projection" rel="stylesheet" type="text/css">
    <link href="{% static "css/animate.css" %}" media="screen,projection" rel="stylesheet" type="text/css">
    <link href="{% static "css/style.css" %}" media="screen,projection" rel="stylesheet" type="text/css">
    <link href="{% static "css/dataurl.css" %}" media="screen,projection" rel="stylesheet" type="text/css">
</head>
<body style="font-family:Coda">
<div id="particles-js"></div>
<div class="navbar-fixed">
    <nav class="light-blue lighten-1" role="navigation">
        <div class="nav-wrapper container">
            <a class="brand-logo" href="http://www.adishankara.ac.in/" target="_blank" id="logo-container"><b>Scrappy</b></a>
            <ul class="right hide-on-med-and-down">
               <li> <a style="text-transform:capitalize">Welcome {{user}}</a> </li>
               <li> <a href="/sellerlogin/">Home</a> </li>
               <li> <a href = "{{ id }}">Logout</a></li>
            </ul>
            <ul class="side-nav" id="nav-mobile">
               <li> <a style="text-transform:capitalize"></li>
               <li> <a href="/sellerlogin/">Home</a> </li>
               <li> <a href = "{{ id }}">Logout</a></li>
            </ul><a class="button-collapse" data-activates="nav-mobile" href="#"><i class="material-icons">menu</i></a>
        </div>
    </nav> 
</div>
<div class="container center row">
    <h3>My Ads</h3>
    <div class="col m8 offset-m2 black-text grey lighten-4">
     <ul class="collapsible popout" data-collapsible="accordion">
    {% for ad in ads %}
      <li>
          <div class="collapsible-header active" style="text-transform: capitalize;">{{ ad.pname }}</div>
          <div class="collapsible-body">
              <span>ID : {{ ad.id }}<br/> Quantity : {{ ad.quantity }} KG <br/> Base Price : {{ ad.price }} </span>
              <br>
              <a href="/sellerlogin/bids/{{ad.id}}" class="btn red">Explore</a><br/><br/>
          </div>
      </li>
    {% endfor %}
  </ul>
    </div>
</div>
</body>
<script>
     //alert('{{ alert }}');
</script>
    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script type='text/javascript' src="{% static "js/init.js" %}"></script>
    <script type='text/javascript' src="{% static "js/materialize.min.js" %}"></script>
    <script type='text/javascript' src="{% static "js/typed.js" %}"></script>
    <script type='text/javascript' src="{% static "js/wow.js" %}"></script>
    <script type='text/javascript' src="{% static "js/particles.js" %}"></script>
    <script type='text/javascript' src="{% static "js/app.js" %}"></script>
</html> 

scrap/scrapapp/templates/scrapapp/email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>Hello {{ user }},</p>
<h2>Welcome to Scrappy !!</h2>
<p>Your account has been registered successfully.</p>
{{message}}
    <br>
<a href="localhost:8000/home/">Click here to continue in Scrappy :)</a>

<button id="myButton" class="float-left submit-button" >Home</button>

<script type="text/javascript">
    document.getElementById("myButton").onclick = function () {
        location.href = "localhost:8000/index/";
    };
</script>


</body>
</html>

scrap/scrapapp/templates/scrapapp/register.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Coda" rel="stylesheet">
    <link href="{% static "css/materialize.css" %}" media="screen,projection" rel="stylesheet" type="text/css">
    <link href="{% static "css/animate.css" %}" media="screen,projection" rel="stylesheet" type="text/css">
    <link href="{% static "css/style.css" %}" media="screen,projection" rel="stylesheet" type="text/css">
    <link href="{% static "css/dataurl.css" %}" media="screen,projection" rel="stylesheet" type="text/css">
</head>
<body style="font-family: Coda">
<div id="particles-js"></div>
<div class="navbar-fixed">
    <nav class="light-blue lighten-1 mynav" role="navigation">
        <div class="nav-wrapper container">
            <a class="brand-logo" href="/index/" target="_blank" id="logo-container"><b>Scrappy</b></a>
            <ul class="right hide-on-med-and-down">
                <li>
                    <a href="/home/">Login</a>
                </li>
            </ul>
            <ul class="side-nav" id="nav-mobile">
                <li>
                    <a href="/home/">Login</a>
                </li>
            </ul><a class="button-collapse" data-activates="nav-mobile" href="#"><i class="material-icons">menu</i></a>
        </div>
    </nav> 
</div>
<div class="container center row">
    <h3>Register</h3>
    <div class="col m3">
      <img src="{% static "img/scrap.png" %}" width="230">
    </div>
    <div class="col m6 s12">
    <form action="" method="post" enctype="multipart/form-data">
    {%csrf_token%}
        <span class="helptext">All Fields are Required.<br/></span>
        <div class="row">
            <div class="input-field col m6">
                <label for="id_username">Username</label>
                <input id="id_username" maxlength="150" name="username" type="text" required /><br />
            </div>
            <div class="input-field col m6">
               <label for="id_password">Password</label>
                <input id="id_password" name="password" type="password" required />
            </div>
        </div>
        <div class="row">
            <div class="input-field col m12">
               <label for="id_email">Email address</label>
                <input id="id_email" maxlength="254" name="email" type="email" />
            </div>
        </div>
        <div class="row">
            <div class="input-field col m12">
               <label for="id_address">Address</label>
                <input id="id_address" maxlength="50" name="address" type="text" required />
            </div>
        </div>
<!--Dealer-->
    {% if form == 'dealer'%}
     
        <div class="row">
             <div class="input-field col m6">
               <label for="id_ph_no">Mobile</label>
                <input id="id_ph_no" maxlength="10" name="ph_no" type="text" required />
            </div>
           
            <div class="input-field col m6">
                <label for="id_city">City</label>
                <input id="id_city" maxlength="20" name="city" type="text" required />
            </div>
        </div>
        <div class="row">
             <div class="input-field col m6">
               <label for="id_pincode">Pincode</label>
                <input id="id_pincode" maxlength="6" name="pincode" type="text" required />
            </div>
            <div class="input-field col m6">
               <label for="id_reg_id">Adhaar ID</label>
               <input id="id_reg_id" maxlength="20" name="reg_id" type="text" required />
            </div>
        </div>
        <div class="row">
        <div class="input-field col m12">
               <label for="id_reg_image center">Profile Picture</label><br>
               <div class="file-field input-field">
                  <div class="btn">
                    <span>File</span>
                    <input type="file" id="id_reg_image" name="reg_image" required>
                  </div>
                  <div class="file-path-wrapper">
                    <input class="file-path validate" type="text">
                  </div>
               </div>
            </div>
        </div>
    <!--Seller-->
    {%else %}
         <div class="row">
             <div class="input-field col m6">
                 <label for="id_city">City:</label>
                 <input id="id_city" maxlength="20" name="city" type="text" required />
            </div>
            <div class="input-field col m6">
                <label for="id_landmark">Landmark:</label>
                <input id="id_landmark" maxlength="30" name="landmark" type="text" required />
            </div>
        </div>
        <div class="row">
             <div class="input-field col m6">
                 <label for="id_ph_no">Mobile</label>
                 <input id="id_ph_no" maxlength="10" name="ph_no" type="text" required />
            </div>
            <div class="input-field col m6">
                <label for="id_pincode">Pincode</label>
                <input id="id_pincode" maxlength="6" name="pincode" type="text" required />
            </div>
        </div>
  {%endif %}

   <!-- {{user.as_p}}
    {{form.as_p}}
    {% if form.errors %}
        {{ form.errors }}
    {% endif %}

    {% if user.errors %}
        {{ user.errors }}
    {% endif %}
   -->
    <input class="btn green" type="submit" id="submitbutton" value="ok"></input>
    {{ status }}


</form>
    </div>
    <div class="col m3">
      <img src="{% static "img/scrapp.png" %}" width="195">
    </div>
{% if error %}
{{ error }}
{% endif %}
<br/>
</body>
<script>
     //alert('{{ alert }}');
</script>
    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script type='text/javascript' src="{% static "js/init.js" %}"></script>
    <script type='text/javascript' src="{% static "js/materialize.min.js" %}"></script>
    <script type='text/javascript' src="{% static "js/typed.js" %}"></script>
    <script type='text/javascript' src="{% static "js/wow.js" %}"></script>
    <script type='text/javascript' src="{% static "js/particles.js" %}"></script>
    <script type='text/javascript' src="{% static "js/app.js" %}"></script>

<script>
            $("#id_username").change(function () {
      var username = $(this).val();
      console.log(username);
      $.ajax({
        url: '/validateuser/',
        data: {
          'username': username
        },
        dataType: 'json',
        success: function (data) {
          if (data.is_taken) {
            alert("A user with this username already exists.");
          }
        }
      });

    });
/*
  $('#submitbutton').click(function (e) {
  e.preventDefault();

    var name = $('#id_username').val();
    var password = $('#id_password').val();
    var email = $('#id_email').val();
    var address = $('#id_address').val();
    var adhar;
    var land;
    console.log(name+password+email+address);
    if('{{form}}'!="dealer")
     {
       var phone=$('#id_ph_no').val();
       var city=$('#id_city').val();
       var pin=$('#id_pincode').val();
       var adhar=$('#id_reg_id').val();
      $.ajax({
        url: '/test/',
        type : 'post',
        dataType: 'json',
        data: {name: name, password: password,address:address,email:email,phone:phone,city:city,pin:pin,adhar:adhar,dealer:"dealer",csrfmiddlewaretoken: '{{ csrf_token }}'},
        success: function(data) {
        console.log("success");
                 },
        failure: function(data) {
        alert('Got an error dude');
        }
        });//ajax close

      }//if
    else
    {
        var phone=$('#id_ph_no').val();
        var city=$('#id_city').val();
        var pin=$('#id_pincode').val();
        var land=$('#id_landmark').val();
        $.ajax({
        url: '/test/',
        type : 'post',
        dataType: 'json',
        data: {name: name, password: password,address:address,email:email,phone:phone,city:city,pin:pin,adhar:adhar,land:land,csrfmiddlewaretoken: '{{ csrf_token }}'},
        success: function(data) {
        console.log("success");
                 },
        failure: function(data) {
        alert('Got an error dude');
        }
        });//ajax close
      }

       window.location.replace('/codeverify/');

    });
*/
    </script>


</html>
   

scrap/scrapapp/templates/scrapapp/seller1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script>

    </script>
</head>
<body>
<h2>Welcome Seller {{user}}</h2>
<class ="myclass">

<form action="" method="post">
    {%csrf_token%}

    <tr><th><label for="id_pname">Pname:</label></th><td><select id="id_pname" name="pname" required>
<option value="" selected="selected">---------</option>
        {% for prod in product %}
<option value="{{prod.id}}">{{prod.pname}}</option>
        {%endfor%}
</select></td></tr>
<tr><th><label for="id_date">Date:</label></th><td><input id="id_date" name="date" type="text" value="2017-03-06 10:45:51" /><input id="initial-id_date" name="initial-date" type="hidd
en" value="{{product.date}}" /></td></tr>
<tr><th><label for="id_quantity">Quantity:</label></th><td><input id="id_quantity" name="quantity" type="number" required /></td></tr>
<tr><th><label for="id_price">Price:</label></th><td><input id="id_price" name="price" type="number" required /></td></tr>





<!--    {% if ads %}
    {{ ads.as_p }}
    {% endif %}-->
    <input type="submit" value="ok"></input>

</form>
</class>
<br>
<a href="/sellerlogin/bids/">my bids</a>
{{ status  }}
<br>
<a href="{{ id }}">logout</a>
</body>
</html>